# Generated by Django 3.1 on 2020-08-21 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('populationRate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('population', models.FloatField()),
                ('food', models.FloatField()),
                ('iron', models.FloatField()),
                ('aluminum', models.FloatField()),
                ('steel', models.FloatField()),
                ('wood', models.FloatField()),
                ('rawUranium', models.FloatField()),
                ('enrichedUranium', models.FloatField()),
                ('oil', models.FloatField()),
                ('construction', models.FloatField()),
                ('research', models.FloatField()),
                ('happiness', models.FloatField()),
                ('crime', models.FloatField()),
                ('military', models.FloatField()),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.government')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.region')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBoost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('food', 'Food'), ('iron', 'Iron'), ('aluminum', 'Aluminum'), ('steel', 'Steel'), ('wood', 'Wood'), ('rawUranium', 'Raw Uranium'), ('enrichedUranium', 'Enriched Uranium'), ('oil', 'Oil')], max_length=100)),
                ('percentage', models.FloatField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.nation')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentBoost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('construction', 'Construction'), ('research', 'Research'), ('happiness', 'Happiness'), ('crime', 'Crime'), ('military', 'Military')], max_length=100)),
                ('percentage', models.FloatField()),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.government')),
            ],
        ),
    ]
