# Generated by Django 3.1 on 2020-08-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0002_government_governmentboost_nation_resourceboost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomeBoost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('food', 'Food'), ('iron', 'Iron'), ('aluminum', 'Aluminum'), ('steel', 'Steel'), ('wood', 'Wood'), ('rawUranium', 'Raw Uranium'), ('enrichedUranium', 'Enriched Uranium'), ('oil', 'Oil')], max_length=100)),
                ('percentage', models.FloatField()),
                ('biome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.biome')),
            ],
        ),
    ]
