# Generated by Django 3.1 on 2020-08-21 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nations', '0003_biomeboost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='aluminum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='construction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='crime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='enrichedUranium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='food',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='government',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nations.government'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='happiness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='iron',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='military',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='oil',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nation',
            name='population',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='rawUranium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='research',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='steel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='wood',
            field=models.FloatField(default=0),
        ),
    ]
