# Generated by Django 3.1 on 2020-08-24 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nations', '0003_biomeboost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBuildingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('desc', models.TextField()),
                ('foodCost', models.IntegerField(default=0)),
                ('ironCost', models.IntegerField(default=0)),
                ('aluminumCost', models.IntegerField(default=0)),
                ('steelCost', models.IntegerField(default=0)),
                ('woodCost', models.IntegerField(default=0)),
                ('rawUraniumCost', models.IntegerField(default=0)),
                ('enrichedUraniumCost', models.IntegerField(default=0)),
                ('oilCost', models.IntegerField(default=0)),
                ('constructionTime', models.IntegerField(verbose_name='Construction Time (in hours)')),
                ('resource', models.CharField(choices=[('food', 'Food'), ('iron', 'Iron'), ('aluminum', 'Aluminum'), ('steel', 'Steel'), ('wood', 'Wood'), ('rawUranium', 'Raw Uranium'), ('enrichedUranium', 'Enriched Uranium'), ('oil', 'Oil')], max_length=254, verbose_name='Producing Resource')),
                ('rpc', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TroopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='nation',
            name='aluminum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='construction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='crime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='enrichedUranium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='food',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='government',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nations.government'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='happiness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='iron',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='military',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='oil',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nation',
            name='population',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='rawUranium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='research',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='steel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='wood',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.troopinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedBuildingTime', models.DateTimeField(auto_now_add=True)),
                ('lastLoad', models.DateTimeField(auto_now=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.resourcebuildinginfo')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.nation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilitaryBuildingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('desc', models.TextField()),
                ('foodCost', models.IntegerField(default=0)),
                ('ironCost', models.IntegerField(default=0)),
                ('aluminumCost', models.IntegerField(default=0)),
                ('steelCost', models.IntegerField(default=0)),
                ('woodCost', models.IntegerField(default=0)),
                ('rawUraniumCost', models.IntegerField(default=0)),
                ('enrichedUraniumCost', models.IntegerField(default=0)),
                ('oilCost', models.IntegerField(default=0)),
                ('constructionTime', models.IntegerField(verbose_name='Construction Time (in hours)')),
                ('housing', models.IntegerField()),
                ('troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.troop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilitaryBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedBuildingTime', models.DateTimeField(auto_now_add=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.militarybuildinginfo')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.nation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
