# Generated by Django 3.1 on 2020-08-24 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0004_auto_20200823_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarybuildinginfo',
            name='troop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.troopinfo'),
        ),
    ]
