# Generated by Django 3.1 on 2020-08-24 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nations', '0005_auto_20200823_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nation', to=settings.AUTH_USER_MODEL),
        ),
    ]
